import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="bg-white shadow-md px-6 py-3 flex gap-6 items-center">
          <a href="/lottery" className="text-purple-700 font-bold hover:underline">Lottery</a>
          <a href="/insurance" className="text-purple-700 font-bold hover:underline">Insurance</a>
          <a href="/profile" className="text-purple-700 font-bold hover:underline">Profile</a>
          <a href="/tracking" className="text-purple-700 font-bold hover:underline">Tracking</a>
          <a href="/auth/login" className="text-purple-700 font-bold hover:underline ml-auto">Login</a>
          <a href="/auth/register" className="text-purple-700 font-bold hover:underline">Register</a>
        </nav>
        {children}
      </body>
    </html>
  );
}
